### ISSUE TITLE
States diverge when playing two local fakeships

### ISSUE THREAD

**Issue by bonbud-macryg** [ashelkovnykov/urbit-chess#129]
In this screenshot ~bud and ~ser play a game, ~bud's latest move never makes it to ~ser's frontend.

![](https://0x0.st/HHg0.png)
  
This was a bug I'd occasionally see while testing on Firefox with two local fakeships, but notably I never saw it after one of the "undo move"-related commits by @rovmug-ticfyn. I got it on every game after just a few moves while testing #127; logging here as a reminder to do a git-bisect to find out where the bad commit is.

**Comment by ashelkovnykov** [comment]
@bonbud-macryg I think that this might be because of inconsistent fake-zod states, since we're in a weird situation where the `develop` branch of `%chess` is made to work with the `develop` branch of `urbit/urbit`, which right now depends on the `edge` pace build of `urbit/vere`.

Just tested every `%chess` feature successfully on `develop` and for #127 after doing the following set of steps:
1. Shut down `~finmep-lanteb`
2. Change `/path/to/piers/finmep-lanteb/.bin/pace` to "edge"
3. Launch `~finmep-lanteb` to download latest version of Vere
4. Shut down `~finmep-lanteb`
5. Copy Vere version `2.3-ad4dae0` to `edge-urbit`
6. Reset pace file back to "soon" (you might be on "live", in which case reset it to that)
7. Create new fake `~tex` using latest live Vere (`v2.1`)
8. Shutdown `~tex`
9. `rm -rf /path/to/pier/tex/.bin`
10. `./edge-urbit dock /path/to/pier/tex`
11. Repeat steps 7 - 10 for fake `~mex`
12. Boot `~tex`
13. Suspend `%webterm`, `%talk`, `%groups`, and `%landscape` (e.g. `|suspend %talk`)
14. `|mount %base`
15. `rm -rf /path/to/pier/tex/base/*`
16. `cp -rfL /path/to/urbit/repo/pkg/arvo/* /path/to/pier/tex/base/`
17. `cp -rfL /path/to/urbit/repo/pkg/base-dev/* /path/to/pier/tex/base/`
18. `|commit %base`
19. `|unmount %base`
20. Repeat steps 12 - 19 for `~mex`
21. `|new-desk %chess` on `~tex`
22. `|mount %chess`
23. `cp -rfL /path/to/urbit/repo/pkg/base-dev/* /path/to/pier/tex/chess/`
24. `cp -rfL /path/to/landscape/repo/pkg/desk-dev/* /path/to/pier/tex/chess/`
25. Build `%chess`
26. Install `%chess`
27. `|commit %chess`
28. `|install our %chess`
29. `:treaty|publish %chess`
30. Upload glob to `%chess`
31. Install `%chess` on `~mex`
32. Test features in Firefox

(Steps 23 & 24 are dumb and annoying - I plan to fix those when splitting the repo into 3 components)

I'll leave the issue open for now, and you can decide if you'd like to go through the rigamarole to confirm the above yourself as well. We're just in this mess because of the UF delaying their release of Vere `2.2` and the matching Arvo until this week, so hopefully we should be back to the normal testing process as of Wednesday April 5th.

**Comment by bonbud-macryg** [comment]
Tested up to 15 moves without issue on two new fresh ships, built with the latest `vere` and latest `urbit-develop` source.
