### ISSUE TITLE
Allow undoing moves and adding back pieces on the practice board

### ISSUE THREAD

**Issue by nallux-dozryl** [ashelkovnykov/urbit-chess#24]
This makes the practice board more useful

**Comment by ashelkovnykov** [comment]
I'm going to close this as a combination of "duplicate" and "won't fix":
- It's a duplicate of #97 in that the practice board would automatically achieve feature parity with the game board (including undos)
- It won't be fixed in that adding pieces back onto the board is so annoying as to be impossible in the context of #97
